Add openid-connect-generic-session-expired action on session expiry before logout
oidc-wp/openid-connect-generic pull request #228
Opened 2020-09-10 16:42 UTC by jkouris

Add openid-connect-generic-session-expired action before to allow consumers to act on the refresh token expiration

### All Submissions:

* [x] Have you followed the [plugin Contributing guideline](https://github.com/oidc-wp/openid-connect-generi/blob/dev/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Added action 'openid-connect-generic-session-expired' to allow client to react to the session expiry (refresh token expired) just before logging the user out and redirecting them back to the login page.    It can be useful in situations where SSO is being used across multiple apps.  In this case the user is logged in with the SSO provider via another app, but has timed out of wordpress.  This allows a hook to re-authenticate them automatically and allow access to the resource based.  The action provides the user and the REDIRECT_URI as parameters to allow any necessary action to be taken on timeout with the url and parameters provided.   

Closes # .

### How to test the changes in this Pull Request:

1. Add the following hook in the client code
    add_action('openid-connect-generic-session-expired', 'expired_method', 10, 2);
2.  Start a session with the OpenID Connect provider via wordpress.   Close the browser without logging out and wait until the token refresh has expired.  
3.  Revisit the wordpress resource and observe the action being fired. 

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

2021-01-13 05:38 UTC, timnolte commented
@jkouris this PR is failing both WordPress coding standards and static analysis. You can run these check with NPM if you have the [local development environment setup](https://github.com/oidc-wp/openid-connect-generic/blob/dev/.github/CONTRIBUTING.md).

2022-02-25 18:31 UTC, timnolte approved these changes

2022-02-25 19:03 UTC, timnolte approved these changes

2022-02-25 19:07 UTC, timnolte requested changes
@jkouris I'd like to include this in the next release that I want to push out soon. Can you update this to resolve the Coding Standards issues. You can find the issues here: https://github.com/oidc-wp/openid-connect-generic/runs/5338133715?check_suite_focus=true Thanks!

2022-02-26 22:49 UTC, jkouris commented
@timnolte I have resolved the coding standards issues and verified it passes when running locally

2022-03-02 00:17 UTC, merged