added define config with OIDC_LOGIN_TYPE and OIDC_CLIENT_SCOPE
oidc-wp/openid-connect-generic pull request #256
Opened 2021-01-08 07:18 UTC by ChloeTigre

### All Submissions:

* [ x] Have you followed the [plugin Contributing guideline](https://github.com/oidc-wp/openid-connect-generi/blob/dev/.github/CONTRIBUTING.md)?
* [ x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [ x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

I add here support for define() settings for two variables: `login_type` and `scope`.

`OIDC_CLIENT_SCOPE` is a space-separated list of scopes.
`OIDC_LOGIN_TYPE` can either be `button` or `auto`. Other values have undefined behaviour.

### How to test the changes in this Pull Request:

1. set `define('OIDC_CLIENT_SCOPE', 'email openid profile')` in your wp-config.php
2. see it shows up in the config and the variable is read-only
3. do the same for `OIDC_LOGIN_TYPE`

### Other information:

* [ x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [ x] Have you successfully run tests with your changes locally?

### Changelog entry

Added two new environment variables:

`OIDC_CLIENT_SCOPE`: a space-separated list of scopes.
`OIDC_LOGIN_TYPE`: can either be `button` or `auto`. Other values have undefined behaviour.

2021-01-11 10:28 UTC, ChloeTigre commented
Hi there, the tests have failed but I have no idea why. It's a straight branch from develop and the changes are really minor.

2021-01-12 12:47 UTC, ChloeTigre commented
/travis_retry

2021-01-12 13:09 UTC, ChloeTigre commented
opening a new issue.

2021-01-13 00:14 UTC, timnolte commented
@ChloeTigre your PR is passing now. Will take a deeper look and consider it for inclusion in the next 3.9 feature release.

2021-01-13 05:14 UTC, timnolte requested changes
@ChloeTigre comments made some changes are required. Thanks!

2021-01-13 05:14 UTC, timnolte commented on includes/openid-connect-generic-settings-page.php
> +				'disabled'    => defined( 'OIDC_ENFORCE_PRIVACY' ),
@ChloeTigre you didn't document in your PR, and didn't add this to the PHPStan bootstap, adding this additional constant. Please remove this or add the missing documentation and additional support.

2021-01-13 05:14 UTC, timnolte commented on includes/openid-connect-generic-settings-page.php
> +				'disabled'    => defined( 'OIDC_LINK_EXISTING_USERS' ),
@ChloeTigre you didn't document in your PR, and didn't add this to the PHPStan bootstap, adding this additional constant. Please remove this or add the missing documentation and additional support.

2021-01-13 05:14 UTC, timnolte commented on includes/openid-connect-generic-settings-page.php
> +				'disabled'    => defined( 'OIDC_CREATE_IF_NOT_EXISTS' ),
@ChloeTigre you didn't document in your PR, and didn't add this to the PHPStan bootstap, adding this additional constant. Please remove this or add the missing documentation and additional support.

2021-01-13 05:14 UTC, timnolte commented on includes/openid-connect-generic-settings-page.php
> +				'disabled'    => defined( 'OIDC_REDIRECT_USER_BACK' ),
@ChloeTigre you didn't document in your PR, and didn't add this to the PHPStan bootstap, adding this additional constant. Please remove this or add the missing documentation and additional support.

2021-01-13 05:14 UTC, timnolte commented on includes/openid-connect-generic-settings-page.php
> +				'disabled'    => defined( 'OIDC_REDIRECT_ON_LOGOUT' ),
@ChloeTigre you didn't document in your PR, and didn't add this to the PHPStan bootstap, adding this additional constant. Please remove this or add the missing documentation and additional support.

2021-01-13 05:14 UTC, timnolte commented on openid-connect-generic.php
> +				'enforce_privacy' => defined( 'OIDC_ENFORCE_PRIVACY' ) ? intval( OIDC_ENFORCE_PRIVACY ) : 0,
@ChloeTigre you didn't document in your PR, and didn't add this to the PHPStan bootstap, adding this additional constant. Please remove this or add the missing documentation and additional support.

2021-01-13 05:14 UTC, timnolte commented on openid-connect-generic.php
> +				'redirect_on_logout' => defined( 'OIDC_REDIRECT_ON_LOGOUT' ) ? intval( OIDC_REDIRECT_ON_LOGOUT ) : 1,
@ChloeTigre you didn't document in your PR, and didn't add this to the PHPStan bootstap, adding this additional constant. Please remove this or add the missing documentation and additional support.

2021-01-13 05:14 UTC, timnolte commented on readme.md
> +- openid login type: `OIDC_LOGIN_TYPE` ('button' or 'auto')
@ChloeTigre please ensure that these labels match those in the plugin settings screen.

2021-01-13 16:21 UTC, ChloeTigre commented
Yes doing that!

2021-01-13 16:55 UTC, ChloeTigre commented
There :) thanks.

2021-07-07 09:20 UTC, ChloeTigre commented
Hey there ! I have no time to care for the README.md change and I am unsure of the desired styling. Can someone take care of this? I'd like to get this merged but it's out of my professional scope at the moment.

2021-12-29 22:05 UTC, timnolte approved these changes

2022-02-25 19:02 UTC, merged