Clean up PHPStan configuration
oidc-wp/openid-connect-generic pull request #420
Opened 2022-07-08 00:50 UTC by szepeviktor

### All Submissions:

* [x] Have you followed the [plugin Contributing guideline](https://github.com/oidc-wp/openid-connect-generi/blob/dev/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Clean up PHPStan configuration.

2022-08-26 03:18 UTC, timnolte requested changes
@szepeviktor these changes cause the static analysis checks to fail due to including the `Uses func_get_args()` check again after it was remove since it never shows up in the code. Also you have made significant changes without much details on why you removed them. My biggest concern was removing `%rootDir%/../../php-stubs/wordpress-stubs/wordpress-stubs.php` from the `bootstrapFiles` or is PHPStan able to autoload these?

2022-08-26 04:41 UTC, szepeviktor commented
> My biggest concern was removing `%rootDir%/../../php-stubs/wordpress-stubs/wordpress-stubs.php` from the `bootstrapFiles` or is PHPStan able to autoload these?

Hello! The package `szepeviktor/phpstan-wordpress` loads WP core stubs.
https://github.com/szepeviktor/phpstan-wordpress/blob/c9fb3dc5e0a964845f6124a9c4394987749c657b/extension.neon#L93-L95

I may have introduced failures. Fixing **now** ...

2022-08-26 04:44 UTC, szepeviktor commented
I hope you like 47 lines of deletion :)

2023-06-23 04:05 UTC, timnolte approved these changes

2023-06-23 04:12 UTC, merged